const products = [
    {
        id: 1,
        name: 'Leche de vaca',
        price: 27.00,
        description: 'Leche entera de vaca',
        imagen:  '/Images/leche.png',
    },
    {
        id: 2,
        name: 'Servilletas',
        price: 40.00,
        description: 'Papel de Baño',
        imagen:  '/Images/papel.png',
    },
    {
        id: 3,
        name: 'Atún de aceite',
        price: 19.00,
        description: 'Atún de aceite en lata',
        imagen:  '/Images/atun.png',
    },
    {
        id: 4,
        name: 'Jabon',
        price: 55.00,
        description: 'Jabon Lavatraste',
        imagen:  '/Images/jabontraste.jpeg',
    },
    {
        id: 5,
        name: 'Jabon para Manos',
        price: 50.00,
        description: 'Jabon Antibacterial',
        imagen:  '/Images/jabonmanos.jpg',
    },
    {
        id: 6,
        name: 'Huevos',
        price: 35.00,
        description: 'Caja de Huevos',
        imagen:  '/Images/huevos.png',
    },
    {
        id: 7,
        name: 'Crema de Mani',
        price: 60.00,
        description: 'Crema de Cacahuate',
        imagen:  '/Images/cremamani.png',
    },
    {
        id: 8,
        name: 'Jugo',
        price: 28.00,
        description: 'Jugo',
        imagen:  '/Images/jugo.png',
    },
    {
        id: 9,
        name: 'Cloralex',
        price: 35.00,
        description: 'Cloro',
        imagen:  '/Images/cloro.jpg',
    },
    {
        id: 10,
        name: 'Fabuloso',
        price: 40.00,
        description: 'Limpiador Liquido',
        imagen:  '/Images/fabuloso.png',
    },
    {
        id: 11,
        name: 'Cereal',
        price: 40.00,
        description: 'Cereal',
        imagen:  '/Images/cereal.png',
    },
    {
        id: 12,
        name: 'Galletas',
        price: 48.00,
        description: 'Caja de Galletas',
        imagen:  '/Images/galletas.jpg',
    },
    {
        id: 13,
        name: 'Desodorante',
        price: 44.00,
        description: 'Desodorante en aerosol',
        imagen:  '/Images/desodorante.png',
    },
    {
        id: 14,
        name: 'Shampoo',
        price: 59.00,
        description: 'Shampoo',
        imagen:  '/Images/shampoo.png',
    },
    {
        id: 15,
        name: 'Aceite',
        price: 36.00,
        description: 'Aceite de Cartamo',
        imagen:  '/Images/aceite.png',
    }
];

export default products;